fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.6.0"
    ntp:
      repo: "https://github.com/puppetlabs/puppetlabs-ntp.git"
      ref: "4.2.0"
    profile_base: "https://github.com/relybv/dirict-profile_base.git"
    profile_nfs: "https://github.com/relybv/dirict-profile_nfs.git"
    profile_mysql: "git://github.com/relybv/dirict-profile_mysql.git"
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"
    nfs: "https://github.com/derdanne/puppet-nfs.git"
    mysql: "https://github.com/puppetlabs/puppetlabs-mysql.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    lvm: "https://github.com/puppetlabs/puppetlabs-lvm.git"
    rsyslog: "https://github.com/saz/puppet-rsyslog.git"
    staging: "https://github.com/nanliu/puppet-staging"
    motd: "https://github.com/puppetlabs/puppetlabs-motd.git"
    augeasproviders_core: "git://github.com/hercules-team/augeasproviders_core.git"
    augeasproviders_shellvar: "git://github.com/hercules-team/augeasproviders_shellvar.git"
    gai: "https://github.com/smoeding/puppet-gai.git"

  symlinks:
    role_db: "#{source_dir}"
