fixtures:
  forge_modules:
     stdlib: "puppetlabs/stdlib"

  repositories:
# role module layout, include profile base and ntp module
    profile_base: "https://github.com/relybv/dirict-profile_base.git"
    profile_nfs: "https://github.com/relybv/dirict-profile_nfs.git"
    profile_mysql: "git://github.com/relybv/dirict-profile_mysql.git"
    ntp: "https://github.com/puppetlabs/puppetlabs-ntp.git"
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"
    nfs: "https://github.com/echocat/puppet-nfs.git"
    mysql: "https://github.com/puppetlabs/puppetlabs-mysql.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    lvm: "https://github.com/puppetlabs/puppetlabs-lvm.git"
    rsyslog: "https://github.com/saz/puppet-rsyslog.git"
    staging: "https://github.com/nanliu/puppet-staging"
    motd: "https://github.com/puppetlabs/puppetlabs-motd.git"
    augeasproviders_core: "git://github.com/hercules-team/augeasproviders_core.git"
    augeasproviders_shellvar: "git://github.com/hercules-team/augeasproviders_shellvar.git"

  symlinks:
    role_db: "#{source_dir}"
