fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"

# role module layout, include profile base and ntp module
    profile_base: "https://github.com/relybv/dirict-profile_base.git"
    ntp: "https://github.com/puppetlabs/puppetlabs-ntp.git"
    profile_mysql: "git://github.com/relybv/dirict-profile_mysql.git"
    mysql: "https://github.com/puppetlabs/puppetlabs-mysql.git"

  symlinks:
    role_db: "#{source_dir}"
